services:
  kairyu:
    build:
      context: .
      dockerfile: build/Dockerfile
      platforms:
        - linux/amd64
    ports:
      - '8090:8090'
      - '8095:8095'
    volumes:
      - ./kairyu.json:/app/kairyu.json
    environment:
      KAIRYU_CONFIG: ./kairyu.json